---
agent_list:
- 10.5.0.4
public_agent_list:
- 10.4.0.4
- 10.3.0.4
oauth_enabled: 'true'
oauth_issuer_url: https://mydomain.auth0.com/
oauth_client_id: client_id
oauth_auth_redirector: https://mydomain.auth0.com
oauth_auth_host: https://mydomain.auth0.com
exhibitor_storage_backend: static
telemetry_enabled: 'true'
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: trumpt-dcos
log_directory: /genconf/logs
master_discovery: static
master_list:
- 10.2.0.4
- 10.2.0.5
- 10.5.0.5
process_timeout: 10000
resolvers:
- 8.8.8.8
- 8.8.4.4
ssh_key_path: /genconf/ssh-key
ssh_port: '22'
ssh_user: sysop
