# genconf/config.yaml
# Use this bootstrap_url value unless you have moved the DC/OS installer assets.
---
agent_list:
- <agent-private-ip-1>
- <agent-private-ip-2>
- <agent-private-ip-3>
bootstrap_url: http://<agent-public-ip>:9000
cluster_name: <cluster-name>
master_discovery: static
master_list:
- <master-private-ip-1>
- <master-private-ip-2>
- <master-private-ip-3>
public_agent_list:
- <public-agent-private-ip>
resolvers:
- 8.8.4.4
- 8.8.8.8
ssh_port: 22
ssh_user: <username>
